
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubepi-user
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepi-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubepi-user
    namespace: kube-system

---

apiVersion: v1
kind: Service
metadata:
  name: kubepi
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 28110
  selector:
    app.kubernetes.io/name: kubepi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepi
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kubepi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubepi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubepi
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
        - name: kubepi
          image: docker.io/kubeoperator/kubepi-server:latest
          #image: kubeoperator/kubepi-server:v1.6.5
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 80
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - name: kubepi-persistent-storage
              mountPath: /var/lib/kubepi
      volumes:
        - name: kubepi-persistent-storage
          hostPath:
            path: /data/kubepi-storage
            type: DirectoryOrCreate
