---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: registry
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: registry
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - "true"
      containers:
      - image: registry:2.8.2
        name: registry
        ports:
          - containerPort: 5000
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/registry
            name: registry-volume
      restartPolicy: Always
      volumes:
        - name: registry-volume
          hostPath:
            path: /data/registry
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: registry
  name: registry
  namespace: registry
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 25000
  type: NodePort
  selector:
    io.kompose.service: registry
status:
  loadBalancer: {}
