---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: otel
spec: {}
status: {}
---
apiVersion: v1
data:
  default: http://mimir
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app.octohelm.tech/name: mimir
  name: endpoint-mimir
  namespace: otel
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app.octohelm.tech/name: mimir
  name: mimir
  namespace: otel
---
apiVersion: v1
data:
  mimir.yaml: |
    multitenancy_enabled: false
    limits:
      max_global_series_per_user: 0
    blocks_storage:
      backend: filesystem
      bucket_store:
        sync_dir: /var/mimir/tsdb-sync
      filesystem:
        dir: /var/mimir/data/tsdb
      tsdb:
        dir: /var/mimir/tsdb
    compactor:
      data_dir: /var/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist
    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
        replication_factor: 1
    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /var/mimir/rules
    server:
      http_listen_port: 9009
      log_level: info
    store_gateway:
      sharding_ring:
        replication_factor: 1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app.octohelm.tech/name: mimir
  name: mimir-config
  namespace: otel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app.octohelm.tech/name: mimir
  name: mimir-storage
  namespace: otel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.octohelm.tech/name: mimir
  name: mimir
  namespace: otel
spec:
  ports:
  - name: http
    port: 9009
    protocol: TCP
    targetPort: http
  selector:
    app: mimir
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    reload.octohelm.tech/configmap: mimir-config,mimir
  creationTimestamp: null
  labels:
    app.octohelm.tech/name: mimir
  name: mimir
  namespace: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  serviceName: mimir-headless
  template:
    metadata:
      annotations:
        hash.configmap.octohelm.tech/mimir: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        hash.configmap.octohelm.tech/mimir-config: 3d56d934e0607a3568af4e6802dcf86e1a8d3370db099e5782b5924ba165a0f8
        reload.octohelm.tech/configmap: mimir-config,mimir
      creationTimestamp: null
      labels:
        app: mimir
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - args:
        - -config.file=/conf/mimir/mimir.yaml
        envFrom:
        - configMapRef:
            name: mimir
        image:  docker.io/grafana/mimir:2.9.0
        name: mimir
        ports:
        - containerPort: 9009
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /var/mimir
          name: mimir-storage
        - mountPath: /conf/mimir/mimir.yaml
          name: mimir-config
          subPath: mimir.yaml
      volumes:
      - name: mimir-storage
        persistentVolumeClaim:
          claimName: mimir-storage
      - configMap:
          name: mimir-config
        name: mimir-config
  updateStrategy: {}
status:
  availableReplicas: 0
  replicas: 0
