---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-backup-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    server: "10.196.10.119"
    path: "/data/nfsshare/backup"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  mysql-backup-pvc
  namespace: model
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: slow
  volumeName: mysql-backup-pv