{
 "title": "Nvidia GPU Metrics",
 "description": "Nvidia GPU Metrics based on the prometheus metrics from github.com/utkuozdemir/nvidia_gpu_exporter",
 "tags": [
  "nvidia",
  "nvidia-smi",
  "nvidia_gpu_exporter",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "label_values(nvidia_smi_memory_total,projectname)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nvidia_smi_memory_total{projectname=\"$project\"},instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_memory_total{instance=\"$instance\",projectname=\"$project\"},uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "P-State",
   "type": "stat",
   "description": "The current performance state for the GPU. States range from P0 (maximum performance) to P12 (minimum performance).",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{pstate}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "stat",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "gauge",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "graph",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "graph",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "graph",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed{uuid=\"$gpu\",instance=\"$instance\",projectname=\"$project\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}